Fix Failure with --no-merge
UnboundLocalError: local variable 'rule' referenced before assignment

Running into an issue when I run 'suricata-update --no-merge'.
Fixed by changing 'rule.id' to 'key' variable since 'rule' is not used in the
loop.'key' is appended to added list i.e. List of rule IDs that have been added.